/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    public TeknisiView teknisiView;
    public PelangganView pelangganView;
    public ServisView servisView;
    public TransaksiView transaksiView;
    public LihatTransaksiView lihatTransaksiView;
    public LaporanTransaksi laporanTransaksi;
    public LaporanTeknisi laporanTeknisi;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuDesktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        itemTeknisi = new javax.swing.JMenuItem();
        itemPelanggan = new javax.swing.JMenuItem();
        servis = new javax.swing.JMenu();
        Transaksi = new javax.swing.JMenu();
        itemInput = new javax.swing.JMenuItem();
        itemLihat = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        tombolLaporanTeknisi = new javax.swing.JMenuItem();
        tombolLaporanTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuDesktop.setBackground(new java.awt.Color(52, 73, 94));

        javax.swing.GroupLayout menuDesktopLayout = new javax.swing.GroupLayout(menuDesktop);
        menuDesktop.setLayout(menuDesktopLayout);
        menuDesktopLayout.setHorizontalGroup(
            menuDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        menuDesktopLayout.setVerticalGroup(
            menuDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(menuDesktop, java.awt.BorderLayout.CENTER);

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setForeground(new java.awt.Color(0, 0, 0));

        master.setBackground(new java.awt.Color(0, 0, 0));
        master.setText("Master");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        itemTeknisi.setText("Teknisi");
        itemTeknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTeknisiActionPerformed(evt);
            }
        });
        master.add(itemTeknisi);

        itemPelanggan.setText("Pelanggan");
        itemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPelangganActionPerformed(evt);
            }
        });
        master.add(itemPelanggan);

        jMenuBar2.add(master);

        servis.setText("Servis");
        servis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servisMouseClicked(evt);
            }
        });
        servis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servisActionPerformed(evt);
            }
        });
        jMenuBar2.add(servis);

        Transaksi.setText("Transaksi");

        itemInput.setText("Input Transaksi");
        itemInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInputActionPerformed(evt);
            }
        });
        Transaksi.add(itemInput);

        itemLihat.setText("Lihat Transaksi");
        itemLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLihatActionPerformed(evt);
            }
        });
        Transaksi.add(itemLihat);

        jMenuBar2.add(Transaksi);

        laporan.setText("Laporan");

        tombolLaporanTeknisi.setText("Data Teknisi");
        tombolLaporanTeknisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLaporanTeknisiActionPerformed(evt);
            }
        });
        laporan.add(tombolLaporanTeknisi);

        tombolLaporanTransaksi.setText("Data Transaksi");
        tombolLaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLaporanTransaksiActionPerformed(evt);
            }
        });
        laporan.add(tombolLaporanTransaksi);

        jMenuBar2.add(laporan);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masterActionPerformed

    private void itemTeknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTeknisiActionPerformed
        // TODO add your handling code here:\
           if (teknisiView == null) {
            teknisiView = new TeknisiView();
            menuDesktop.add(teknisiView);
        } else {
            teknisiView.toFront();
        }
        teknisiView.setVisible(true);
    }//GEN-LAST:event_itemTeknisiActionPerformed

    private void itemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPelangganActionPerformed
        // TODO add your handling code here:
        if (pelangganView == null) {
            pelangganView = new PelangganView();
            menuDesktop.add(pelangganView);
        } else {
            pelangganView.toFront();
        }
        pelangganView.setVisible(true);
    }//GEN-LAST:event_itemPelangganActionPerformed

    private void servisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_servisActionPerformed

    private void servisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servisMouseClicked
        // TODO add your handling code here:
        if (servisView == null) {
            servisView = new ServisView();
            menuDesktop.add(servisView);
        } else {
            servisView.toFront();
        }
        servisView.setVisible(true);
        
    }//GEN-LAST:event_servisMouseClicked

    private void itemInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInputActionPerformed
        // TODO add your handling code here:
        if (transaksiView == null) {
            transaksiView = new TransaksiView();
            menuDesktop.add(transaksiView);
        } else {
            transaksiView.toFront();
        }
        transaksiView.setVisible(true);
    }//GEN-LAST:event_itemInputActionPerformed

    private void itemLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLihatActionPerformed
        // TODO add your handling code here:
        if (lihatTransaksiView == null) {
            lihatTransaksiView = new LihatTransaksiView();
            menuDesktop.add(lihatTransaksiView);
        } else {
            lihatTransaksiView.toFront();
        }
        lihatTransaksiView.setVisible(true);
    }//GEN-LAST:event_itemLihatActionPerformed

    private void tombolLaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLaporanTransaksiActionPerformed
        // TODO add your handling code here:
        if (laporanTransaksi == null) {
            laporanTransaksi = new LaporanTransaksi();
            menuDesktop.add(laporanTransaksi);
        } else {
            laporanTransaksi.toFront();
        }
        laporanTransaksi.setVisible(true);
    }//GEN-LAST:event_tombolLaporanTransaksiActionPerformed

    private void tombolLaporanTeknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLaporanTeknisiActionPerformed
        // TODO add your handling code here:
        if (laporanTeknisi == null) {
            laporanTeknisi = new LaporanTeknisi();
            menuDesktop.add(laporanTeknisi);
        } else {
            laporanTeknisi.toFront();
        }
        laporanTeknisi.setVisible(true);
    }//GEN-LAST:event_tombolLaporanTeknisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Transaksi;
    private javax.swing.JMenuItem itemInput;
    private javax.swing.JMenuItem itemLihat;
    private javax.swing.JMenuItem itemPelanggan;
    private javax.swing.JMenuItem itemTeknisi;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenu master;
    private javax.swing.JDesktopPane menuDesktop;
    private javax.swing.JMenu servis;
    private javax.swing.JMenuItem tombolLaporanTeknisi;
    private javax.swing.JMenuItem tombolLaporanTransaksi;
    // End of variables declaration//GEN-END:variables
}
