/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;
    
import controller.PelangganController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;
import main.App;
import model.Pelanggan;
/**
 *
 * @author ASUS
 */
public class PelangganView extends javax.swing.JInternalFrame {
    
    private final Pelanggan pelanggan;
    private List<Pelanggan> listPelanggan;
    private final PelangganController pelangganController;
    /**
     * Creates new form PelangganView
     */
    
    public PelangganView() {
        initComponents();
        
        pelanggan = new Pelanggan();
        pelangganController = new PelangganController(this);
        pelangganController.enableForm2(true);
        refreshTable();
        initListener();
    }
    
    public JTextField getTextId() {
        return textId;
    }
    
    public JTextField getTextNama() {
        return textNama;
    }
    
    public JTextField getTextNo() {
        return textNo;
    }
    
    public JTextField getTextEmail() {
        return textEmail;
    }
    
    public JTextField getTextAlamat() {
        return textAlamat;
    }

    public JButton getTombolHapus() {
        return tombolHapus;
    }

    public JButton getTombolSimpan() {
        return tombolSimpan;
    }

    public JButton getTombolUbah() {
        return tombolUbah;
    }

    public JTable getTabelPelanggan() {
        return tabelPelanggan;
    }
    
    private void refreshTable() {
        listPelanggan = App.masterService.getAllPelanggan(); // memanggil interface
        // memasukkan nilai list ke inner class
        tabelPelanggan.setModel(new PelangganTableModel(listPelanggan));
    }
    
    private void initListener(){ // memindahkan nilai di tabel ke form
        tabelPelanggan.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            pelangganController.loadData(pelanggan, listPelanggan);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textAlamat = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tombolSimpan = new javax.swing.JButton();
        tombolReset = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();

        setClosable(true);
        setTitle("Input Data Pelanggan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(127, 140, 141));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Pelanggan");
        jPanel1.add(jLabel5);

        textId.setBackground(new java.awt.Color(255, 255, 255));
        textId.setForeground(new java.awt.Color(0, 0, 0));
        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });
        jPanel1.add(textId);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);

        textNama.setBackground(new java.awt.Color(255, 255, 255));
        textNama.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textNama);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No HP");
        jPanel1.add(jLabel2);

        textNo.setBackground(new java.awt.Color(255, 255, 255));
        textNo.setForeground(new java.awt.Color(0, 0, 0));
        textNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNoActionPerformed(evt);
            }
        });
        jPanel1.add(textNo);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        jPanel1.add(jLabel3);

        textEmail.setBackground(new java.awt.Color(255, 255, 255));
        textEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textEmail);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);

        textAlamat.setBackground(new java.awt.Color(255, 255, 255));
        textAlamat.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textAlamat);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(127, 140, 141));

        tombolSimpan.setBackground(new java.awt.Color(52, 73, 94));
        tombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(tombolSimpan);

        tombolReset.setBackground(new java.awt.Color(52, 73, 94));
        tombolReset.setForeground(new java.awt.Color(255, 255, 255));
        tombolReset.setText("Reset");
        tombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolResetActionPerformed(evt);
            }
        });
        jPanel2.add(tombolReset);

        tombolUbah.setBackground(new java.awt.Color(52, 73, 94));
        tombolUbah.setForeground(new java.awt.Color(255, 255, 255));
        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });
        jPanel2.add(tombolUbah);

        tombolHapus.setBackground(new java.awt.Color(52, 73, 94));
        tombolHapus.setForeground(new java.awt.Color(255, 255, 255));
        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });
        jPanel2.add(tombolHapus);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(127, 140, 141));

        tabelPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        tabelPelanggan.setForeground(new java.awt.Color(0, 0, 0));
        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelanggan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNoActionPerformed

    private void tombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolResetActionPerformed
        // TODO add your handling code here:
        pelangganController.clearForm();
        pelangganController.enableForm2(true);
    }//GEN-LAST:event_tombolResetActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        if (!pelangganController.validasiKode(textId.getText())) {
            return;
        }
        if (pelangganController.validasiInput()) {
            pelanggan.setId(textId.getText());
            pelanggan.setNama(textNama.getText());
            pelanggan.setNoHp(textNo.getText());
            pelanggan.setEmail(textEmail.getText());
            pelanggan.setAlamat(textAlamat.getText());

            App.masterService.simpanPelanggan(pelanggan);
            JOptionPane.showMessageDialog(this, "Data pelanggan berhasil disimpan !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
            
        }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        // TODO add your handling code here:
         if (pelangganController.validasiInput()) {
            pelanggan.setId(textId.getText());
            pelanggan.setNama(textNama.getText());
            pelanggan.setNoHp(textNo.getText());
            pelanggan.setEmail(textEmail.getText());
            pelanggan.setAlamat(textAlamat.getText());
            
            App.masterService.ubahPelanggan(pelanggan);
            JOptionPane.showMessageDialog(this, "Data pelanggan berhasil diubah !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
         }
    }//GEN-LAST:event_tombolUbahActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
            pelanggan.setId(textId.getText());
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data ini?", "Konfirmasi", JOptionPane.WARNING_MESSAGE);
            if(konfirmasi==0){
                App.masterService.hapusPelanggan(pelanggan);
                JOptionPane.showMessageDialog(this, "Data pelanggan berhasil dihapus !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
                pelangganController.clearForm();
            }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textIdActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        App.menuView.pelangganView = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        // TODO add your handling code here:
        pelangganController.enableForm(true);
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNo;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolReset;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
    
    public class PelangganTableModel extends AbstractTableModel {

        private List<Pelanggan> listPelanggan = new ArrayList<>();

        private final String HEADER[] = {"ID Pelanggan", "Nama", "No HP", "Email", "Alamat"};

        public PelangganTableModel(List<Pelanggan> listPelanggan) {
            this.listPelanggan = listPelanggan;
        }

        @Override
        public int getRowCount() { // jumlah baris
            return listPelanggan.size();
        }

        @Override
        public int getColumnCount() { // jumlah kolom
            return HEADER.length;
        }

        @Override
        public String getColumnName(int i) { // nama kolom
            return HEADER[i];
        }

        @Override
        public Object getValueAt(int i, int i1) { // mengisi data
            Pelanggan p = listPelanggan.get(i); // baris
            switch (i1) { // kolom
                case 0:
                    return p.getId();
                case 1:
                    return p.getNama();
                case 2:
                    return p.getNoHp();
                case 3:
                    return p.getEmail();
                case 4:
                    return p.getAlamat();
                default:
                    return null;
            }
        }
    }
}

