/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ServisController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;
import main.App;
import model.Servis;
import model.Pelanggan;
import model.Teknisi;
/**
 *
 * @author ASUS
 */
public class ServisView extends javax.swing.JInternalFrame {
    
    private final Servis servis;
    private Pelanggan pelanggan;
    private Teknisi teknisi;
    private List<Servis> listServis;
    private ServisController servisController;

    /**
     * Creates new form ServisView
     */
    public ServisView() {
        initComponents();
        
        servis = new Servis();
        pelanggan = new Pelanggan();
        teknisi = new Teknisi();
        servisController = new ServisController(this);
        servisController.loadPelanggan();
        servisController.loadTeknisi();
        servisController.enableForm(true);
        refreshTable();
        initListener();
    }
    
    public JComboBox<String> getComboPelanggan() {
        return comboPelanggan;
    }

    public void setComboPelanggan(JComboBox<String> comboPelanggan) {
        this.comboPelanggan = comboPelanggan;
    }
    
    public JComboBox<String> getComboTeknisi() {
        return comboTeknisi;
    }

    public void setComboTeknisi(JComboBox<String> comboTeknisi) {
        this.comboTeknisi = comboTeknisi;
    }

    public JTable getTabelServis() {
        return tabelServis;
    }

    public void setTabelServis(JTable tabelServis) {
        this.tabelServis = tabelServis;
    }

    public JTextField getTextNoServis() {
        return textNoServis;
    }

    public void setTextNoServis(JTextField textNoServis) {
        this.textNoServis = textNoServis;
    }
    
    public JComboBox getComboJenis() {
        return comboJenis;
    }
    
        public JTextField getTextDeskripsi() {
        return textDeskripsi;
    }
    
    public JTextField getTextHarga() {
        return textHarga;
    }

    public JButton getTombolHapus() {
        return tombolHapus;
    }

    public void setTombolHapus(JButton tombolHapus) {
        this.tombolHapus = tombolHapus;
    }

    public JButton getTombolSimpan() {
        return tombolSimpan;
    }

    public void setTombolSimpan(JButton tombolSimpan) {
        this.tombolSimpan = tombolSimpan;
    }

    public JButton getTombolUbah() {
        return tombolUbah;
    }

    public void setTombolUbah(JButton tombolUbah) {
        this.tombolUbah = tombolUbah;
    }
    
    private void refreshTable(){
        listServis = App.masterService.getAllServis();
        tabelServis.setModel(new ServisTableModel(listServis));
    }

    private void initListener(){
        tabelServis.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            servisController.loadData(servis, listServis);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNoServis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboPelanggan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboTeknisi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboJenis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textDeskripsi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textHarga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tombolSimpan = new javax.swing.JButton();
        tombolReset = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelServis = new javax.swing.JTable();

        setClosable(true);
        setTitle("Input Data Servis");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(127, 140, 141));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No Servis");
        jPanel1.add(jLabel1);

        textNoServis.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textNoServis);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pelanggan");
        jPanel1.add(jLabel2);

        comboPelanggan.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(comboPelanggan);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teknisi");
        jPanel1.add(jLabel3);

        comboTeknisi.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(comboTeknisi);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Servis");
        jPanel1.add(jLabel4);

        comboJenis.setForeground(new java.awt.Color(0, 0, 0));
        comboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardware", "Software" }));
        jPanel1.add(comboJenis);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Deskripsi Servis");
        jPanel1.add(jLabel5);

        textDeskripsi.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(textDeskripsi);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");
        jPanel1.add(jLabel6);

        textHarga.setBackground(new java.awt.Color(255, 255, 255));
        textHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHargaActionPerformed(evt);
            }
        });
        jPanel1.add(textHarga);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(127, 140, 141));

        tombolSimpan.setBackground(new java.awt.Color(52, 73, 94));
        tombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(tombolSimpan);

        tombolReset.setBackground(new java.awt.Color(52, 73, 94));
        tombolReset.setForeground(new java.awt.Color(255, 255, 255));
        tombolReset.setText("Reset");
        tombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolResetActionPerformed(evt);
            }
        });
        jPanel2.add(tombolReset);

        tombolUbah.setBackground(new java.awt.Color(52, 73, 94));
        tombolUbah.setForeground(new java.awt.Color(255, 255, 255));
        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });
        jPanel2.add(tombolUbah);

        tombolHapus.setBackground(new java.awt.Color(52, 73, 94));
        tombolHapus.setForeground(new java.awt.Color(255, 255, 255));
        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });
        jPanel2.add(tombolHapus);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(127, 140, 141));

        tabelServis.setBackground(new java.awt.Color(255, 255, 255));
        tabelServis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelServis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelServisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelServis);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHargaActionPerformed

    private void tombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolResetActionPerformed
        // TODO add your handling code here:
        servisController.clearForm();
        servisController.enableForm(true);
    }//GEN-LAST:event_tombolResetActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        if (!servisController.validasiKode(textNoServis.getText())) {
            return;
        }
        if (servisController.validasiInput()) {
            pelanggan = App.masterService.getByNamePelanggan(comboPelanggan.getSelectedItem().toString());
            teknisi = App.masterService.getByNameTeknisi(comboTeknisi.getSelectedItem().toString());
            servis.setIdServis(textNoServis.getText());
            servis.setPelanggan(pelanggan);
            servis.setTeknisi(teknisi);
            servis.setDeskripsi(textDeskripsi.getText());
            servis.setHarga(Double.parseDouble(textHarga.getText()));
            String selectedValue = (String) comboJenis.getSelectedItem();
            servis.setJenis(comboJenis.getSelectedItem().toString());

            App.masterService.simpanServis(servis);
            JOptionPane.showMessageDialog(this, "Data servis berhasil disimpan !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
            
        }
        try {
                double harga = Double.parseDouble(textHarga.getText());
                servis.setHarga(harga);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Harga harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        // TODO add your handling code here:
        if (servisController.validasiInput()) {
            pelanggan = App.masterService.getByNamePelanggan(comboPelanggan.getSelectedItem().toString());
            teknisi = App.masterService.getByNameTeknisi(comboTeknisi.getSelectedItem().toString());
            servis.setIdServis(textNoServis.getText());
            servis.setPelanggan(pelanggan);
            servis.setTeknisi(teknisi);
            servis.setDeskripsi(textDeskripsi.getText());
            servis.setHarga(Double.parseDouble(textHarga.getText()));
            String selectedValue = (String) comboJenis.getSelectedItem();
            servis.setJenis(comboJenis.getSelectedItem().toString());

            App.masterService.ubahServis(servis);
            JOptionPane.showMessageDialog(this, "Data servis berhasil diubah !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
            
        }
    }//GEN-LAST:event_tombolUbahActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        servis.setIdServis(textNoServis.getText());
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data ini?", "Konfirmasi", JOptionPane.WARNING_MESSAGE);
            if(konfirmasi==0){
                App.masterService.hapusServis(servis);
                JOptionPane.showMessageDialog(this, "Data servis berhasil dihapus !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
                servisController.clearForm();
            }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tabelServisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelServisMouseClicked
        // TODO add your handling code here:
        servisController.enableForm2(true);
    }//GEN-LAST:event_tabelServisMouseClicked

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        App.menuView.servisView = null;
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboJenis;
    private javax.swing.JComboBox<String> comboPelanggan;
    private javax.swing.JComboBox<String> comboTeknisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelServis;
    private javax.swing.JTextField textDeskripsi;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textNoServis;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolReset;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
    
    public class ServisTableModel extends AbstractTableModel{

        private List<Servis> listServis = new ArrayList<>();
        private final String HEADER[] = {"No Servis", "Pelanggan", "Teknisi", "Jenis", "Diskripsi", "Harga"};

        public ServisTableModel(List<Servis> listServis) {
            this.listServis = listServis;
        }
        
        @Override
        public int getRowCount() {
            return listServis.size();
        }

        @Override
        public int getColumnCount() {
            return HEADER.length;
        }

        @Override
        public String getColumnName(int i) {
            return HEADER[i];
        }

        @Override
        public Object getValueAt(int i, int i1) {
            Servis s = listServis.get(i);
            switch(i1){
                case 0:
                    return s.getIdServis();
                case 1:
                    return s.getPelanggan().getNama();
                case 2:
                    return s.getTeknisi().getNama();
                case 3:
                    return s.getJenis();
                case 4:
                    return s.getDeskripsi();
                case 5:
                    return s.getHarga();
                default:
                    return null;
            }
        }
        
    }
    
}
